import { NewsSource, StoryCluster } from '../types';

export interface MediaDossier {
  id: number;
  name: string;
  shortName: string;
  logoUrl?: string;
  camp: string;
  campColor: string;
  ownership: string;
  founded: string;
  audience: string;
  editorialProfile: string;
  strengths: string[];
  blindspotsTendency: string[];
  factualityScore: number; // dynamically computed
  polarizationScore: number; // dynamically computed
  averageTone: string;
  websiteUrl: string;
}

export const MEDIA_DOSSIERS: Record<string, MediaDossier> = {
  'Коммерсантъ': {
    id: 5,
    name: 'Издательский дом «Коммерсантъ»',
    shortName: 'Коммерсантъ',
    logoUrl: 'https://www.kommersant.ru/favicon.ico',
    camp: 'Деловая/Центристская',
    campColor: '#1ca369',
    ownership: 'АО «Коммерсантъ»',
    founded: '1989 г.',
    audience: 'Бизнес-элита, инвесторы, топ-менеджмент',
    editorialProfile: 'Авторитетная деловая газета. Специализируется на объективном фактчекинге макроэкономики, законодательства, корпоративных балансов и сырьевых рынков.',
    strengths: ['Глубокий фактчекинг экономических документов', 'Оценка регуляторных рисков для бизнеса', 'Сдержанный безоценочный язык'],
    blindspotsTendency: ['Осторожность в освещении прямых конфликтов внутри силовых ведомств'],
    factualityScore: 91,
    polarizationScore: 24,
    averageTone: 'Прагматичная / Нейтральная',
    websiteUrl: 'https://kommersant.ru',
  },
  'РБК': {
    id: 6,
    name: 'Медиахолдинг «РБК»',
    shortName: 'РБК',
    logoUrl: 'https://s.rbk.ru/v1_static_common/common-2.1.201/images/favicon.png',
    camp: 'Деловая/Центристская',
    campColor: '#1ca369',
    ownership: 'Группа ЕСН',
    founded: '1993 г.',
    audience: 'Финансисты, технологический сектор, предприниматели',
    editorialProfile: 'Деловой портал с акцентом на финансовые индикаторы, опросы отраслевых экспертов, технологические тренды и влияние санкций.',
    strengths: ['Быстрое сопоставление данных независимых экспертов', 'Качественная инфографика и диаграммы'],
    blindspotsTendency: ['Фокус почти исключительно на экономических последствиях'],
    factualityScore: 89,
    polarizationScore: 26,
    averageTone: 'Деловая / Информативная',
    websiteUrl: 'https://rbc.ru',
  },
  'Reuters World': {
    id: 8,
    name: 'Международное агентство Reuters',
    shortName: 'Reuters',
    logoUrl: 'https://www.reuters.com/pf/resources/images/reuters/favicon.ico',
    camp: 'Проукраинская/Внешняя',
    campColor: '#1969ae',
    ownership: 'Thomson Reuters (Великобритания / Канада)',
    founded: '1851 г.',
    audience: 'Мировые финансовые рынки и правительства',
    editorialProfile: 'Крупнейшее мировое агентство. Освещает глобальную геополитику, решения стран G7, санкционную политику и международную торговлю.',
    strengths: ['Прямой доступ к инсайдам министерств финансов США и ЕС', 'Глобальная проверка международных транзакций'],
    blindspotsTendency: ['Выраженный уклон в сторону позиций Вашингтона и Брюсселя, игнорирование аргументов оппонентов'],
    factualityScore: 88,
    polarizationScore: 48,
    averageTone: 'Западно-центричная / Аналитическая',
    websiteUrl: 'https://reuters.com',
  },
  'ТАСС': {
    id: 1,
    name: 'Информационное агентство ТАСС',
    shortName: 'ТАСС',
    logoUrl: 'https://tass.ru/favicon.ico',
    camp: 'Официально-лоялистская',
    campColor: '#1969ae',
    ownership: 'Государственное информационное агентство (ФГУП)',
    founded: '1904 г.',
    audience: 'Госструктуры, СМИ, массовый читатель',
    editorialProfile: 'Главный государственный первоисточник официальных документов, указов, заявлений министерств и ведомств РФ.',
    strengths: ['Первоисточник официальных данных и прямых цитат должностных лиц', 'Широкая сеть аккредитованных журналистов'],
    blindspotsTendency: ['Полное отсутствие критики внутренней госполитики, сглаживание кризисных явлений'],
    factualityScore: 85,
    polarizationScore: 56,
    averageTone: 'Официально-протокольная',
    websiteUrl: 'https://tass.ru',
  },
  'РИА Новости': {
    id: 2,
    name: 'РИА Новости (МИА «Россия сегодня»)',
    shortName: 'РИА Новости',
    logoUrl: 'https://ria.ru/favicon.ico',
    camp: 'Официально-лоялистская',
    campColor: '#1969ae',
    ownership: 'ФГУП МИА «Россия сегодня»',
    founded: '1941 г.',
    audience: 'Массовая российская и зарубежная аудитория',
    editorialProfile: 'Оперативные молнии, репортажи и авторские колонки с последовательной поддержкой внешней и внутренней политики РФ.',
    strengths: ['Высокая скорость публикации оперативных сводок', 'Фото и видеорепортажи'],
    blindspotsTendency: ['Выраженный отбор фактов в пользу успехов госпрограмм и неудач оппонентов'],
    factualityScore: 82,
    polarizationScore: 62,
    averageTone: 'Патриотическая / Наступательная',
    websiteUrl: 'https://ria.ru',
  },
  'Медуза': {
    id: 7,
    name: 'Интернет-издание «Meduza»',
    shortName: 'Медуза',
    logoUrl: 'https://meduza.io/favicon.ico',
    camp: 'Либерально-оппозиционная',
    campColor: '#ef9630',
    ownership: 'SIA Medusa Project (Латвия)',
    founded: '2014 г.',
    audience: 'Оппозиционная и эмигрантская аудитория',
    editorialProfile: 'Общественно-политическое издание. Фокусируется на антивоенной повестке, правах человека, расследованиях и критике властей РФ.',
    strengths: ['Глубокие фактчекинговые разборы законодательных запретов', 'Публикация альтернативных мнений и свидетельств'],
    blindspotsTendency: ['Систематическое игнорирование успехов импортозамещения и позитивных сдвигов в РФ'],
    factualityScore: 81,
    polarizationScore: 65,
    averageTone: 'Критическая / Тревожная',
    websiteUrl: 'https://meduza.io',
  },
  'Рыбарь': {
    id: 4,
    name: 'Военно-аналитический проект «Рыбарь»',
    shortName: 'Рыбарь',
    logoUrl: 'https://rybar.ru/favicon.ico',
    camp: 'Военкоры/Z',
    campColor: '#db233d',
    ownership: 'Независимый военно-аналитический центр',
    founded: '2018 г.',
    audience: 'Свыше 1.2 млн подписчиков, эксперты по ВПК и геополитике',
    editorialProfile: 'Глубокий анализ военных карт, тактики, поставок вооружений, спутниковых снимков и конфликтов на Ближнем Востоке и в Европе.',
    strengths: ['Высокая точность геопривязки и визуализация боевых карт', 'Анализ военного потенциала сторон'],
    blindspotsTendency: ['Исключительно милитаристский фокус с игнорированием дипломатических сценариев'],
    factualityScore: 80,
    polarizationScore: 68,
    averageTone: 'Военно-стратегическая',
    websiteUrl: 'https://rybar.ru',
  },
  'Readovka': {
    id: 3,
    name: 'Медиахолдинг «Readovka»',
    shortName: 'Readovka',
    logoUrl: 'https://readovka.news/favicon.ico',
    camp: 'Военкоры/Z',
    campColor: '#db233d',
    ownership: 'Частное патриотическое медиа',
    founded: '2014 г.',
    audience: 'Свыше 2 млн читателей в Telegram',
    editorialProfile: 'Острые бытовые, военные и социальные темы с яркой эмоциональной патриотической подачей.',
    strengths: ['Быстрая реакция на происшествия и запросы жителей регионов', 'Сводки с передовой'],
    blindspotsTendency: ['Использование эмоционально заряженной лексики и высокая степень поляризации'],
    factualityScore: 75,
    polarizationScore: 78,
    averageTone: 'Эмоционально-боевая',
    websiteUrl: 'https://readovka.news',
  },
};

export const MOCK_SOURCES: NewsSource[] = Object.values(MEDIA_DOSSIERS).map((d) => ({
  id: d.id,
  name: d.shortName,
  url: d.websiteUrl,
  feed_type: d.name.includes('Рыбарь') || d.name.includes('Readovka') ? 'telegram' : 'rss',
  default_camp: d.camp,
  is_active: true,
  factuality_score: d.factualityScore,
  bias_score: d.polarizationScore,
  coverage_count: d.id * 14 + 40,
}));

export const MOCK_STORIES: StoryCluster[] = [
  {
    id: 1,
    title: 'Саммит БРИКС 2026: Запуск независимой системы трансграничных расчетов BRICS Pay',
    summary: 'Лидеры стран БРИКС на саммите утвердили протокол запуска децентрализованной платежной платформы на базе цифровых валют центральных банков (CBDC). Система направлена на прямые расчеты в национальных валютах в обход SWIFT и клиринговых систем США.',
    sentiment: 0.32,
    category: 'Экономика',
    consensus_score: 84,
    polarization_score: 52,
    article_count: 14,
    sources_count: 6,
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updated_at: new Date().toISOString(),
    timeline: [
      { time: '09:30', title: 'Открытие пленарной сессии', description: 'Министры финансов представили итоговый проект клирингового протокола.' },
      { time: '14:00', title: 'Подписание меморандума', description: 'Все 10 стран утвердили регламент пилотных расчетов в цифровых рублях и юанях.' },
      { time: '17:15', title: 'Реакция МВФ и рынков', description: 'Курс нацвалют стран БРИКС укрепился на 0.8% на фоне новостей.' },
    ],
    media: [
      {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1000&q=80',
        caption: 'Презентация протокола BRICS Pay на пленарном заседании саммита',
        source_name: 'ТАСС',
      },
      {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=1000&q=80',
        caption: 'Цифровые валюты и мультивалютный клиринговый шлюз',
        source_name: 'Коммерсантъ',
      },
    ],
    political_vectors: [
      {
        camp: 'Официально-лоялистская',
        percentage: 35,
        tone: 'Триумфальная',
        position: 'Ключевой исторический прорыв в построении многополярного финансового мира и окончательной дедолларизации торговли стран Глобального Юга.',
      },
      {
        camp: 'Военкоры/Z',
        percentage: 20,
        tone: 'Одобрительно-сдержанная',
        position: 'Важный шаг для защиты оборонной промышленности и параллельного импорта от вторичных западных санкций.',
      },
      {
        camp: 'Деловая/Центристская',
        percentage: 25,
        tone: 'Прагматичная',
        position: 'Снижает комиссии на 1.8-2.4%, но потребует до 18 месяцев на интеграцию банковских шлюзов и регулирование курсовых рисков.',
      },
      {
        camp: 'Либерально-оппозиционная',
        percentage: 12,
        tone: 'Скептическая',
        position: 'Указывают на скрытые противоречия между Китаем и Индией в вопросе доминирования юаня в расчетной корзине.',
      },
      {
        camp: 'Проукраинская/Внешняя',
        percentage: 8,
        tone: 'Критическая',
        position: 'Заявляют о фрагментации мировой финансовой системы и рисках обхода санкционного режима G7.',
      },
    ],
    verified_facts: [
      'Меморандум о внедрении платформы подписали представители всех 10 государств-участников БРИКС.',
      'Тестовые транзакции в нацвалютах успешно прошли между банками РФ, ОАЭ, Китая и Бразилии.',
      'Платформа использует открытый исходный код распределенного реестра без единого сервера в юрисдикции Запада.',
    ],
    blindspots: [
      'Государственные СМИ умалчивают о сохранении резервов части стран-участниц в казначейских облигациях США.',
      'Западные СМИ игнорируют 40% рост объемов взаимной торговли между участниками за последний квартал.',
    ],
    quotes: [
      {
        quote: 'Мы создаем финансовую архитектуру, защищенную от политического диктата и односторонних блокировок.',
        speaker_or_source: 'Председатель оргкомитета БРИКС',
        source_url: 'https://tass.ru/ekonomika',
      },
      {
        quote: 'Главный вызов — поддержание стабильности курсов валют корзины при высокой волатильности сырьевых рынков.',
        speaker_or_source: 'Главный аналитик РБК Инвестиции',
        source_url: 'https://rbc.ru',
      },
    ],
    articles: [
      { id: 101, title: 'БРИКС запускает BRICS Pay: итоги ключевого заседания', source_name: 'ТАСС', url: 'https://tass.ru', published_at: new Date().toISOString() },
      { id: 102, title: 'Как новая платежная система изменит внешнюю торговлю РФ', source_name: 'Коммерсантъ', url: 'https://kommersant.ru', published_at: new Date().toISOString() },
      { id: 103, title: 'Финансовая автономия: ответ на вторичные санкции', source_name: 'Readovka', url: 'https://t.me/readovkanews', published_at: new Date().toISOString() },
      { id: 104, title: 'BRICS payments platform faces liquidity questions', source_name: 'Reuters', url: 'https://reuters.com', published_at: new Date().toISOString() },
    ],
  },
  {
    id: 2,
    title: 'Прорыв в отечественной микроэлектронике: запуск опытной линии литографии 28 нм',
    summary: 'В Зеленограде завершены пуско-наладочные испытания первого отечественного сканера литографии для пластин 300 мм с проектными нормами до 28 нм. Комплекс готов к опытно-промышленной серии процессоров общего и специального назначения.',
    sentiment: 0.68,
    category: 'Технологии',
    consensus_score: 92,
    polarization_score: 30,
    article_count: 9,
    sources_count: 5,
    created_at: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    updated_at: new Date().toISOString(),
    timeline: [
      { time: '11:00', title: 'Официальный запуск чистой зоны', description: 'Первая кремниевая пластина прошла экспонирование на отечественном сканере.' },
      { time: '15:20', title: 'Экспертная оценка Минпромторга', description: 'Подтвержден выход годных кристаллов свыше 62% на контрольной партии.' },
    ],
    media: [
      {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80',
        caption: 'Чистая комната и лазерный блок позиционирования кремниевых пластин',
        source_name: 'РИА Новости',
      },
    ],
    political_vectors: [
      {
        camp: 'Официально-лоялистская',
        percentage: 45,
        tone: 'Энтузиазм',
        position: 'Полная победа технологического суверенитета: ликвидация ключевой зависимости в критической инфраструктуре.',
      },
      {
        camp: 'Деловая/Центристская',
        percentage: 35,
        tone: 'Сдержанно-позитивная',
        position: 'Событие стратегическое, но себестоимость чипов первого поколения будет в 2.1 раза выше тайваньских аналогов до масштабирования производства.',
      },
      {
        camp: 'Военкоры/Z',
        percentage: 20,
        tone: 'Патриотическая',
        position: 'Отечественная компонентная база гарантирует бесперебойное производство систем наведения и БПЛА нового поколения.',
      },
      {
        camp: 'Либерально-оппозиционная',
        percentage: 0,
        tone: 'нет данных',
        position: 'Нет данных в предоставленных материалах',
      },
      {
        camp: 'Проукраинская/Внешняя',
        percentage: 0,
        tone: 'нет данных',
        position: 'Нет данных в предоставленных материалах',
      },
    ],
    verified_facts: [
      'Оборудование разработано консорциумом НИИ при поддержке Минпромторга.',
      'Первая тестовая партия кремниевых пластин показала выход годных кристаллов более 62%.',
    ],
    blindspots: [
      'Лагеря "Либерально-оппозиционный" и "Проукраинская/Внешняя" полностью не освещали запуск отечественной линии.',
      'Официальные отчеты не раскрывают точный список поставщиков лазерной оптики.',
    ],
    quotes: [
      {
        quote: 'Это фундаментальный рубеж, отделяющий страны-потребители от технологических лидеров мира.',
        speaker_or_source: 'Руководитель департамента радиоэлектроники',
        source_url: 'https://ria.ru',
      },
    ],
    articles: [
      { id: 201, title: 'Зеленоград запустил первую 28-нм чистую комнату', source_name: 'РИА Новости', url: 'https://ria.ru', published_at: new Date().toISOString() },
      { id: 202, title: 'Экономика отечественного чипа: цены и рынки сбыта', source_name: 'РБК', url: 'https://rbc.ru', published_at: new Date().toISOString() },
      { id: 203, title: 'Технологический щит: как это усилит ВПК', source_name: 'Рыбарь', url: 'https://t.me/rybar', published_at: new Date().toISOString() },
    ],
  },
  {
    id: 3,
    title: 'Реформа энергетического баланса: Введение гибких экспортных пошлин на газ и СПГ',
    summary: 'Правительство представило проект корректировки налога на добычу полезных ископаемых (НДПИ) и механизма плавающих экспортных пошлин на сжиженный природный газ с привязкой к спотовым котировкам азиатских хабов.',
    sentiment: -0.18,
    category: 'Экономика',
    consensus_score: 58,
    polarization_score: 74,
    article_count: 11,
    sources_count: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    updated_at: new Date().toISOString(),
    media: [
      {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1000&q=80',
        caption: 'СПГ-танкер ледового класса в акватории Северного морского пути',
        source_name: 'Коммерсантъ',
      },
    ],
    political_vectors: [
      {
        camp: 'Деловая/Центристская',
        percentage: 40,
        tone: 'Озабоченная',
        position: 'Дополнительное фискальное изъятие может сократить инвестиционные программы компаний Новатэк и Газпром по новым арктическим СПГ-проектам.',
      },
      {
        camp: 'Официально-лоялистская',
        percentage: 30,
        tone: 'Нейтрально-обоснованная',
        position: 'Мера призвана гарантировать наполнение федерального бюджета и удержать внутренние цены на газ для промышленности.',
      },
      {
        camp: 'Либерально-оппозиционная',
        percentage: 20,
        tone: 'Критическая',
        position: 'Считают решение свидетельством дефицита бюджета и роста давления на ключевые сырьевые корпорации.',
      },
      {
        camp: 'Проукраинская/Внешняя',
        percentage: 10,
        tone: 'Негативная',
        position: 'Прогнозируют снижение конкурентоспособности российского СПГ на китайском и индийском направлениях.',
      },
      {
        camp: 'Военкоры/Z',
        percentage: 0,
        tone: 'нет данных',
        position: 'Нет данных в предоставленных материалах',
      },
    ],
    verified_facts: [
      'Поправки в Налоговый кодекс поступят на рассмотрение Госдумы в весеннюю сессию.',
      'Базовая ставка пошлины составит 0% при цене ниже $280 за тыс. кубометров.',
    ],
    blindspots: [
      'Официальные комментарии не приводят прогноз падения дивидендных выплат для частных инвесторов.',
      'Лагерь "Военкоры/Z" не уделил внимания налоговой инициативе.',
    ],
    quotes: [
      {
        quote: 'Баланс между доходами казны и инвестиционным стимулом отрасли будет строго соблюден.',
        speaker_or_source: 'Министерство финансов РФ',
        source_url: 'https://kommersant.ru',
      },
    ],
    articles: [
      { id: 301, title: 'Минфин предложил новую шкалу пошлин на СПГ', source_name: 'Коммерсантъ', url: 'https://kommersant.ru', published_at: new Date().toISOString() },
      { id: 302, title: 'Акции энергетических гигантов отреагировали снижением на 1.4%', source_name: 'РБК', url: 'https://rbc.ru', published_at: new Date().toISOString() },
    ],
  },
];
